### ISSUE TITLE
train bug

### ISSUE THREAD

**Issue by zpz915** [Ahmednull/L2CS-Net#37]
python train.py \
>  --dataset mpiigaze \
>  --snapshot output/snapshots \
>  --gpu 0 \
>  --num_epochs 50 \
>  --batch_size 16 \
>  --lr 0.00001 \
>  --arch ResNet101 \
>  --alpha 1
Loading data.
45000 items removed from dataset that have an angle > 0
Traceback (most recent call last):
  File "train.py", line 276, in <module>
    train_loader_gaze = DataLoader(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 268, in __init__
    sampler = RandomSampler(dataset, generator=generator)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 102, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0

**Comment by zpz915** [comment]
i read the code,find dataset=Mpiigaze(testlabelpathombined,args.gazeMpiimage_dir, transformations, True, fold) give 5 paramters ,but class Mpiigaze(Dataset): 
  def __init__(self, pathorg, root, transform, train, angle,fold=0):  accept 6 paramters  ,is  there any bug?

**Comment by zpz915** [comment]
when i guess angel=180,the train also meet other bug:
Traceback (most recent call last):
  File "train.py", line 299, in <module>
    {'params': get_ignored_params(model, args.arch), 'lr': 0},
TypeError: get_ignored_params() takes 1 positional argument but 2 were given

**Comment by yakhyo** [comment]
hi @zpz915 , have you succeeded training the model. I am also facing the same issue.

**Comment by forlayo** [comment]
Same issue here, any solutions ?

**Comment by yakhyo** [comment]
@forlayo , I succeeded training Gaze360 and going to release it soon and adding mobilenet new backbone as well.

**Comment by tiamo405** [comment]
I tried to download the dataset but it seems like the dataset is too big, can anyone split the dataset for me around 5gb so I can download it?

**Comment by yakhyo** [comment]
@tiamo405 ,  MPIIFaceGaze is relatively smaller than Gaze360.

**Comment by tiamo405** [comment]
> @tiamo405 , MPIIFaceGaze is relatively smaller than Gaze360.

MPIIFaceGaze not folder Label, link download: https://www.mpi-inf.mpg.de/departments/computer-vision-and-machine-learning/research/gaze-based-human-computer-interaction/its-written-all-over-your-face-full-face-appearance-based-gaze-estimation

**Comment by tiamo405** [comment]
link folder 940Mb: http://datasets.d2.mpi-inf.mpg.de/MPIIGaze/MPIIFaceGaze.zip

**Comment by ipsampling** [comment]
I have identified and resolved issues in the code, and understand why using the Gaze360 dataset can result in successful training while using the MPIIFaceGaze dataset reports errors. This is because MPIIFaceGaze data processing lacks an angle parameter, and all data with angles less than 0 degrees are filtered out.

**Comment by NuoZ** [comment]
> 我已经识别并解决了代码中的问题，并了解了为什么使用 Gaze360 数据集可以成功训练，而使用 MPIIFaceGaze 数据集报告错误。这是因为 MPIIFaceGaze 数据处理缺少 angle 参数，所有角度小于 0 度的数据都会被过滤掉。

Hello, so how did you solve the problem, just delete the parameter or add the code to handle the angle parameter?

**Comment by yakhyo** [comment]
@NuoZ , i resolved the problem and reproduced some of the results.

**Comment by ipsampling** [comment]
> > 我已经识别并解决了代码中的问题，并了解了为什么使用 Gaze360 数据集可以成功训练，而使用 MPIIFaceGaze 数据集报告错误。这是因为 MPIIFaceGaze 数据处理缺少 angle 参数，所有角度小于 0 度的数据都会被过滤掉。
> 
> 您好，那么您是怎么解决问题的，只是删除参数还是添加代码来处理 angle 参数呢？
like this dataset=Mpiigaze(testlabelpathombined,args.gazeMpiimage_dir, transformations, True,180, fold)

**Comment by shojint** [comment]
Sorry. This is my first pull request, so I was a bit clumsy. Please feel free to look at my commit.
